version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REGISTRY
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REGISTRY/go-server:$IMAGE_TAG ./golang
      - docker build -t $REGISTRY/php-server:$IMAGE_TAG ./php
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REGISTRY/go-server:$IMAGE_TAG
      - docker push $REGISTRY/php-server:$IMAGE_TAG
